version: "3.7"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ayon"]
      interval: 5s
      timeout: 5s
      retries: 5

    expose: [5432]

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "db:/var/lib/postgresql/data"

    environment:
      - "POSTGRES_USER=ayon"
      - "POSTGRES_PASSWORD=ayon"
      - "POSTGRES_DB=ayon"

  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5

    expose: [6379]


  server:
    image: ynput/ayon:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/info"]
      interval: 10s
      timeout: 2s
      retries: 3

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    # uncomment for older versions of Docker (>4.0.0) and comment out above "depends on" section.
    #depends_on:
      #- postgres
      #- redis

    expose: [5000]
    ports: ["5000:5000"]

    volumes:
      - "./addons:/addons"
      - "./storage:/storage"

      # comment out the following line on Windows
      - "/etc/localtime:/etc/localtime:ro"

      # uncomment the following line if you need to work on the backend code
      # - "./backend:/backend"

  worker:
    hostname: ash_worker_01
    image: ghcr.io/dimension-studio/ayon-ash:latest
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

    environment:
      - "AYON_API_KEY=${AYON_API_KEY}"
      - "AYON_SERVER_URL=${AYON_SERVER_URL}"



#  processor:
#    container_name: dim-processor
#    image: ghcr.io/dimension-studio/ayon-dim-ftrack-processor:1.1.10
#    restart: unless-stopped
#    environment:
#      - "AYON_SERVER_URL=${AYON_SERVER_URL}"
#      - "AYON_API_KEY=${AYON_API_KEY}"
#      - "AYON_ADDON_NAME=dim-ftrack"
#      - "AYON_ADDON_VERSION=1.1.10"
#
#  leecher:
#    container_name: dim-leecher
#    image: ghcr.io/dimension-studio/ayon-dim-ftrack-leecher:1.1.10
#    restart: unless-stopped
#    environment:
#      - "AYON_SERVER_URL=${AYON_SERVER_URL}"
#      - "AYON_API_KEY=${AYON_API_KEY}"
#      - "AYON_ADDON_NAME=dim-ftrack"
#      - "AYON_ADDON_VERSION=1.1.10"


volumes:
  db: {}
